thanks_agent = ["Hope you have a great day, bye.",
                "Hope you have a good day, bye.",
                "Nice talking to you, have a nice day.",
                "You're welcome.",
                "Bye.",
                "Goodbye.",
                "You too. Bye.",
                "Hope I made some good suggestions.",
                "Ok great bye.",
                "Great, have a good day, goodbye.",
                "Glad I could help bye.",
                "Glad I could help. Bye.",
                "You are welcome bye now.",
                "Ok, have a good day.",
                "Your welcome.",
                "Bye now.",
                "Glad to help.",
                "Okay, have a good day."]

thanks_user = ["Thanks for all the help.",
                "Thanks, it was nice talking to you.",
                "Thanks a lot for your recommendations.",
                "Thanks.",
                "Thank you.",
                "Thanks you, bye.",
                "Thanks for your help.",
                "Thank you for your help today.",
                "Thanks a lot for your help in finding something.",
                "Thanks for the help.",
                "Thank you so much.",
                "Thanks for all the help."]