movie_agent = ["It was my pleasure to help.",
                "I'm happy to have been able to assist.",
                "No problem, I'm glad I could help.",
                "I'm glad I could make a difference.",
                "I'm glad I could be of service.",
                "It was my pleasure to assist you.",
                "I'm glad I could provide some assistance.",
                "You're welcome. I'm always happy to help with movie recommendations.",
                "It was my pleasure to provide some suggestions. I hope you enjoy the movies I recommended.",
                "I'm glad I could assist with your movie selection. Let me know if you have any other questions or need further recommendations.",
                "I'm always happy to assist with movie recommendations.",
                "I'm glad I could provide some movie recommendations for you. Let me know if you have any feedback or need further suggestions.",
                "I'm glad I could be of service with your movie selection. I hope you enjoy the movies I recommended.",
                "You're welcome.",
                "Hope I made some good suggestions.",
                "Glad to help.",
              ]

movie_user = ["Thanks for all the help.",
              "Thanks for the advice, I'll check them.",
              "Thanks a lot for your recommendations.",
              "Thanks.",
              "Thank you.",
              "Thanks a lot for your help in finding something.",
              "Thank you so much.",
              "Thank you so much for the recommendations. I really appreciate your help.",
              "Thank you for your recommendation.",
              "I'm grateful for your suggestions.",
              "Thanks for the recommendations. I'm excited to try out some of the films you suggested.",
              "I really appreciate your help with movie recommendations.",
              "I appreciate your recommendations.",
              "Thanks for your help with movie suggestions.",
              "I'm grateful for your assistance with movie recommendations.",
              "I appreciate your help with movie suggestions.",
             ]


coat_agent = ["It was my pleasure to help.",
              "I'm happy to have been able to assist.",
              "No problem, I'm glad I could help.",
              "I'm glad I could make a difference.",
              "I'm glad I could be of service.",
              "It was my pleasure to assist you.",
              "I'm glad I could provide some assistance.",
              "You're welcome. I'm always happy to help with coats recommendations.",
              "It was my pleasure to provide some suggestions. I hope you enjoy the coats I recommended.",
              "I'm glad I could assist with your coats selection. Let me know if you have any other questions or need further recommendations.",
              "I'm always happy to assist with coats recommendations.",
              "I'm glad I could provide some coats recommendations for you. Let me know if you have any feedback or need further suggestions.",
              "I'm glad I could be of service with your coats selection. I hope you enjoy the coats I recommended.",
              "You're welcome.",
              "Hope I made some good suggestions.",
              "Glad to help."
              ]


coat_user = ["Thank you so much for the recommendations.",
              "Your suggestions were really helpful.",
              "I really appreciate your advice.",
              "Thanks for taking the time to help me out.",
              "I'm so grateful for your recommendations.",
              "Thank you for your kind assistance.",
              "Thanks for all the help.",
              "Thanks for the advice, I'll check them.",
              "Thanks a lot for your recommendations.",
              "Thanks.",
              "Thank you.",
              "Thanks a lot for your help in finding something.",
              "Thank you so much.",
              "Thank you so much for the recommendations. I really appreciate your help.",
              "Thank you for your recommendation.",
              "Thanks for the recommendations. I'm excited to try out some of the coats you suggested.",
              "I really appreciate your help with coats recommendations.",
              "I'm grateful for your assistance with coats recommendations.",
              "I appreciate your help with coats suggestions."
             ]